### ISSUE TITLE
Latest release includes CLJS dependency and compiled test output

### ISSUE THREAD

**Issue by danielcompton** [logaan/vlad#24]
I noticed running a lein deps tree that vlad pulls in a dependency on ClojureScript. It should probably be set to `:scope "provided"` to exclude it from downstream consumers? I also noticed that the compiled test file is being included in the JAR, as it is at `resources/test/test.js` which is included by default in Leiningen. It could be good for compilation to go to a different location, or to exclude the test folder from the JAR?

I can provide a PR for these when I get time.

**Comment by logaan** [comment]
Sorry it's taken a while to get back to you, I've been busy with a new job. I've given you commit access so you can make the changes if you find the time.

btw. thanks for putting together The REPL. It's a good read.
